version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - node-app
    networks:
      - mynetwork

  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge